### ISSUE TITLE
default.xml not loading correct parameters

### ISSUE THREAD

**Issue by dkcyw** [ThornyFFXI/Stylist#3]
I have modified default.xml changing only the noblinkself parameter. I want it set to false.
```
		<noblinkself>false</noblinkself>
		<noblinktarget>true</noblinktarget>
		<noblinkothers>false</noblinkothers>
```

However, stylist still loads its "factory" default (noblinkself loads as true apparently). I added a line in _HorixonXI > Game > scripts > default.txt_ for **/stylist reload** yet the issue persists. 

Issue does not persist if I instead I manually **/stylist reload** in-game.

Another workaround I found to correct for auto loading is to create a second xml which I named _main.xml_. Adding a line in _default.txt_ with **/stylist load main** loads the correct parameters. However, it appears to want to load _default.xml_ anyway. See attached picture. Yet it indeed functions the way I expected and loads noblinkself as false.

![stylist_xml](https://github.com/ThornyFFXI/Stylist/assets/123147852/8b415813-5fe3-4761-ac36-28cdfd4aad90)

Edit: I have noticed that when first time loading Character 1, the workaround noted above works fine. However, when swapping to any other Character, then the _default.xml_ does not load correctly. At this point I have to manually type in **/sl self off**

**Comment by ThornyFFXI** [comment]
Should be fixed in 1.17.
